services:
  postgres:
    restart: always
    image: postgres:14-alpine
    ports:
      - 6432:5432
    volumes:
      - ~/apps/postgres:/var/lib/postgresql/data
    environment:
      - POSTGRES_PASSWORD=analyzerpass
      - POSTGRES_USER=analyzeruser
      - POSTGRES_DB=analyzerdb
#  api:
#    image: api
#    build:
#      context: .
#      dockerfile: API/Dockerfile
